import { NextRequest, NextResponse } from "next/server";

export const dynamic = "force-dynamic";
export const revalidate = 0;

// Default structured job function categories
export const DEFAULT_FUNCTION_CATEGORIES = [
  {
    id: "software-engineering",
    categoryName: "Software Engineering",
    iconName: "Terminal",
    subFunctions: [
      "Full Stack Engineer",
      "Backend Engineer",
      "Frontend Software Engineer",
      "Python Engineer",
      "Java Engineer",
      "C/C++ Engineer",
      ".Net Engineer",
      "Systems Engineer",
      "DevOps",
      "Mobile Engineer",
      "QA / Test Automation",
      "Rust Engineer",
      "Golang Developer",
    ],
    patterns: [
      "*Software Engineer*",
      "*Software Developer*",
      "*Full Stack*",
      "*Fullstack*",
      "*Full-Stack*",
      "*Backend*",
      "*Back End*",
      "*Back-End*",
      "*Frontend*",
      "*Front End*",
      "*Front-End*",
      "*Web Developer*",
      "*Python Developer*",
      "*Python Engineer*",
      "*Java Developer*",
      "*Java Engineer*",
      "*C++*",
      "*C/C++*",
      "*.NET Developer*",
      "*.NET Engineer*",
      "*Dotnet*",
      "*C# Developer*",
      "*C# Engineer*",
      "*Systems Engineer*",
      "*System Engineer*",
      "*DevOps*",
      "*Platform Engineer*",
      "*Infrastructure Engineer*",
      "*Mobile Developer*",
      "*Mobile Engineer*",
      "*iOS Developer*",
      "*iOS Engineer*",
      "*Android Developer*",
      "*Android Engineer*",
      "*React Native*",
      "*Flutter*",
      "*QA Engineer*",
      "*Quality Assurance Engineer*",
      "*SDET*",
      "*Test Automation*",
      "*Automation Engineer*",
      "*Rust Developer*",
      "*Rust Engineer*",
      "*Golang*",
      "*Go Developer*",
      "*Go Engineer*",
      "*Firmware Engineer*",
      "*Embedded Software*",
      "*Embedded Engineer*",
    ],
  },
  {
    id: "data-ai-ml",
    categoryName: "Data & AI / ML",
    iconName: "BrainCircuit",
    subFunctions: [
      "Data Analyst",
      "Data Scientist",
      "Data Engineer",
      "Machine Learning Engineer",
      "AI Engineer",
      "Machine Learning/AI Researcher",
      "Machine Learning, Deep Learning",
      "LLM Engineer",
      "Machine Learning, Computer Vision",
      "NLP Engineer",
      "AI Prompt Engineer",
    ],
    patterns: [
      "*Data Analyst*",
      "*Data Analytics*",
      "*BI Analyst*",
      "*Business Intelligence Analyst*",
      "*Data Scientist*",
      "*Data Science*",
      "*Applied Scientist*",
      "*Decision Scientist*",
      "*Data Engineer*",
      "*Data Platform*",
      "*ETL Developer*",
      "*Data Warehouse*",
      "*Machine Learning*",
      "ML *",
      "* ML *",
      "* ML/*",
      "* ML-*",
      "* (ML)*",
      "* ML",
      "*MLOps*",
      "*Deep Learning*",
      "AI *",
      "* AI *",
      "* AI/*",
      "* AI-*",
      "* (AI)*",
      "* AI",
      "*Artificial Intelligence*",
      "*Generative AI*",
      "*GenAI*",
      "*Gen AI*",
      "*LLM*",
      "*NLP*",
      "*Computer Vision*",
      "*Prompt Engineer*",
      "*AI Agent*",
    ],
  },
  {
    id: "cybersecurity-cloud",
    categoryName: "Cybersecurity & Cloud",
    iconName: "ShieldAlert",
    subFunctions: [
      "Cyber Security Engineer",
      "Cloud Security Engineer",
      "Network Security Engineer",
      "Cloud Architect",
      "Site Reliability Engineer (SRE)",
      "Infrastructure Engineer",
      "Security Analyst",
    ],
    patterns: [
      "*Cyber Security*",
      "*Cybersecurity*",
      "*Cloud Security*",
      "*Network Security*",
      "*Security Engineer*",
      "*Security Analyst*",
      "*Security Architect*",
      "*Information Security*",
      "*Infosec*",
      "*AppSec*",
      "*Application Security*",
      "*DevSecOps*",
      "*SOC Analyst*",
      "*Penetration Tester*",
      "*Cloud Architect*",
      "*Cloud Engineer*",
      "*AWS Engineer*",
      "*Azure Engineer*",
      "*GCP Engineer*",
      "*Site Reliability*",
      "SRE *",
      "* SRE *",
      "* SRE",
    ],
  },
  {
    id: "product-design",
    categoryName: "Product & Design",
    iconName: "Palette",
    subFunctions: [
      "Product Manager",
      "Technical Program Manager",
      "Product Designer",
      "UI/UX Designer",
      "Scrum Master / Agile Coach",
      "Design Systems Engineer",
    ],
    patterns: [
      "*Product Manager*",
      "*Technical Program Manager*",
      "TPM *",
      "* TPM *",
      "* TPM",
      "*Product Designer*",
      "*UI/UX*",
      "*UI Designer*",
      "*UX Designer*",
      "*UX Researcher*",
      "*User Experience*",
      "*User Interface*",
      "*Interaction Designer*",
      "*Design Systems*",
      "*Scrum Master*",
      "*Agile Coach*",
    ],
  },
  {
    id: "business-ops",
    categoryName: "Business & Ops",
    iconName: "LineChart",
    subFunctions: [
      "Account Executive",
      "Sales Development Rep",
      "Marketing Specialist",
      "Operations Associate",
      "Financial Analyst",
      "Growth Strategist",
    ],
    patterns: [
      "*Account Executive*",
      "*Sales Development Representative*",
      "*Sales Development Rep*",
      "SDR *",
      "* SDR *",
      "* SDR",
      "*Business Development Representative*",
      "BDR *",
      "* BDR *",
      "* BDR",
      "*Enterprise Sales*",
      "*Growth Marketing*",
      "*Product Marketing*",
      "*Marketing Specialist*",
      "*Digital Marketing*",
      "*Business Operations*",
      "*Revenue Operations*",
      "*RevOps*",
      "*Financial Analyst*",
      "*Finance Analyst*",
      "*FP&A*",
    ],
  },
  {
    id: "leadership-exec",
    categoryName: "Engineering Leadership & Architecture",
    iconName: "Layers",
    subFunctions: [
      "Software Architect",
      "Staff Engineer",
      "Principal Engineer",
      "Tech Lead",
      "VP of Engineering",
      "Engineering Manager",
      "Head of Engineering",
      "CTO",
    ],
    patterns: [
      "*Software Architect*",
      "*Solutions Architect*",
      "*Staff Engineer*",
      "*Principal Engineer*",
      "*Tech Lead*",
      "*Technical Lead*",
      "*Engineering Manager*",
      "*Director of Engineering*",
      "*VP of Engineering*",
      "*Head of Engineering*",
      "*Chief Technology Officer*",
      "CTO *",
      "* CTO *",
      "* CTO",
    ],
  },
];

// In-memory runtime store for custom configurations (can also sync with DB)
let activeFunctionCategories = [...DEFAULT_FUNCTION_CATEGORIES];

export async function GET() {
  return NextResponse.json({
    success: true,
    categories: activeFunctionCategories,
    allPatterns: Array.from(
      new Set(activeFunctionCategories.flatMap((c) => c.patterns))
    ),
    allSubFunctions: Array.from(
      new Set(activeFunctionCategories.flatMap((c) => c.subFunctions))
    ),
  });
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    if (body.categories && Array.isArray(body.categories)) {
      activeFunctionCategories = body.categories;
      return NextResponse.json({
        success: true,
        message: "Job function categories updated successfully",
        categories: activeFunctionCategories,
      });
    }

    if (body.resetToDefault) {
      activeFunctionCategories = [...DEFAULT_FUNCTION_CATEGORIES];
      return NextResponse.json({
        success: true,
        message: "Reset to default job functions successfully",
        categories: activeFunctionCategories,
      });
    }

    return NextResponse.json(
      { error: "Invalid request payload" },
      { status: 400 }
    );
  } catch (err: any) {
    return NextResponse.json(
      { error: err?.message || "Failed to update job functions" },
      { status: 500 }
    );
  }
}
